# pull official base image
FROM node:alpine

ARG COOKIEKEY
ARG COOKIESECRET

ENV COOKIE_KEY=${COOKIEKEY}
ENV COOKIE_SECRET=${COOKIESECRET}

ARG REDISHOST
ARG REDISPORT
ARG REDISPASSWORD
ARG REDIS_URL

ENV REDIS_HOST=${REDISHOST}
ENV REDIS_PORT=${REDISPORT}
ENV REDIS_PASSWORD=${REDISPASSWORD}
ENV REDIS_URL=${REDIS_URL}

# set working directory
WORKDIR /app

# add app
COPY . ./

# install app dependencies
RUN npm install

# run build
RUN npm run build

CMD [ "node", "index" ]