version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      COOKIEKEY: _sid
      COOKIESECRET: "1664xczxrgwy24&124"